#! /bin/sh

sxhkd &
sxhkd -c /home/vesaliuz/.config/sxhkd/bspwm.sxhkdrc &
compton -b --config /home/vesaliuz/.config/compton/compton.conf &
variety && wal -i $(cat $HOME/.config/variety/wallpaper/wallpaper.jpg.txt) &
/home/vesaliuz/.config/polybar/launch.sh
