#! /bin/sh

# source the colors.
source "${HOME}/.cache/wal/colors.sh"

# Set the border colors.
bspc config normal_border_color "$color1"
bspc config active_border_color "$color2"
bspc config focused_border_color "$color15"
# Use the line below if you are on bspwm >= 0.9.4
bspc config presel_feedback_color "$color1"
# Use the line below if you are on bspwm < 0.9.4
bspc config presel_border_color "$color1"
sxhkd &
sxhkd -c ${HOME}/.config/sxhkd/bspwm.sxhkdrc &

bspc monitor -d alpha bravo charlie delta

bspc config border_width          3
bspc config window_gap            12


bspc config split_ratio           0.50
bspc config borderless_monocle    true
bspc config gapless_monocle       true
bspc config top_padding           22
bspc config bottom_padding        22

# assign deskto to applications
bspc rule -a systemsettings desktop=\alpha
bspc rule -a thunderbird desktop=\alpha
bspc rule -a firefoxdeveloperedition desktop=\bravo follow=on
bspc rule -a firefox desktop=\bravo follow=on
bspc rule -a Atom desktop=\charlie
bspc rule -a Code desktop=\charlie
bspc rule -a Lollypop desktop=\delta
bspc rule -a retroarch desktop=\delta follow=on
bspc rule -a VirtualBox Manager desktop=\delta follow=on
bspc rule -a VirtualBox Machine desktop=\delta follow=on

# applications rules
bspc rule -a Conky state=floating manage=off lower=on
bspc rule -a Plasma state=floating manage=off layer=normal
bspc rule -a plasmashell sticky=on layer=above state=floating
bspc rule -a albert state=floating focus=on follow=on
bspc rule -a Pavucontrol state=floating sticky=on
bspc rule -a feh state=floating
bspc rule -a VirtualBox Manager state=fullscreen
bspc rule -a VirtualBox Machine state=fullscreen
