-- An applications menu
-- Required depends: awesome-freedesktop or xdg_menu
-- awesome-freedesktop : automatic
-- xdg_menu : manual
-- Your choice

local awful = require("awful")
local gears = require("gears")
local beautiful = require("beautiful")
local apps = require('configuration.apps')
local hotkeys_popup = require('awful.hotkeys_popup').widget


terminal = apps.default.terminal
editor = os.getenv("EDITOR") or "vim"
editor_cmd = terminal .. " -e " .. editor



-- Theming Menu
beautiful.menu_font = "SFNS Display Regular 10"
beautiful.menu_submenu = '' -- ➤

-- icon theme is in `awesome/theme/default-theme.lua`
-- Search for `theme.icon_theme`

-- Check first if freedesktop module is installed
-- `awesome-freedesktop-git` is in AUR
-- https://github.com/lcpz/awesome-freedesktop
-- Check on your distro's repo

-- Checks if module exists, also checks syntax. Returns false if syntax error
local function isModuleAvailable(name)
  if package.loaded[name] then
    return true
  else
    for _, searcher in ipairs(package.searchers or package.loaders) do
      local loader = searcher(name)
      if type(loader) == 'function' then
        package.preload[name] = loader
        return true
      end
    end
    return false
  end
end

-- Create a launcher widget and a main menu
myawesomemenu = {
  { "Hotkeys", function() hotkeys_popup.show_help(nil, awful.screen.focused()) end },
  { "Edit config", editor_cmd .. " " .. awesome.conffile },
  { "Restart", awesome.restart },
  { "Quit", function() awesome.quit() end },
}


-- Screenshot menu
local screenshot = {
  {"Full", apps.bins.fullShot },
  {"Area", apps.bins.areaShot },
  {"Select", apps.bins.selectShot }
}

-- Terminal menu
local terminal = {
  {"termite", "termite"},
  {"xterm", "xterm"},
}

-- Generate a list of app
if isModuleAvailable("freedesktop") == true then

  -- A menu generated by awesome-freedesktop
  -- https://github.com/lcpz/awesome-freedesktop

  local freedesktop = require("freedesktop")
  local menubar = require("menubar")

  mymainmenu = freedesktop.menu.build({
    icon_size = 16,
    before = {
      { "Terminal", terminal, menubar.utils.lookup_icon("utilities-terminal") },
      -- other triads can be put here
    },
    after = {
      {"Awesome", myawesomemenu--[[, "/usr/share/awesome/icons/awesome32.png"--]]},
      {"Take a Screenshot", screenshot},
      {"End Session", function() _G.exit_screen_show() end},
      -- other triads can be put here
    }
  })
  mylauncher = awful.widget.launcher({ image = beautiful.awesome_icon, menu = mymainmenu })
  -- Menubar configuration


else

  -- A menu generated by xdg_menu

  -- Replace with the list generated by xdg_menu
 
 local menu98edb85b00d9527ad5acebe451b3fae6 = {
     {"Albert", "albert"},
     {"Application Finder", "xfce4-appfinder", "/usr/share/icons/gnome/16x16/actions/edit-find.png" },
     {"Archive Manager", "file-roller "},
     {"Ark", "ark ", "/usr/share/icons/hicolor/48x48/apps/ark.png" },
     {"Calculator", "gnome-calculator"},
     {"Characters", "/usr/bin/gnome-characters"},
     {"Clocks", "gnome-clocks"},
     {"Disks", "gnome-disks"},
     {"Filelight", "filelight ", "/usr/share/icons/hicolor/16x16/apps/filelight.png" },
     {"Files", "nautilus --new-window "},
     {"Fonts", "gnome-font-viewer "},
     {"GVim", "gvim -f ", "/usr/share/icons/hicolor/48x48/apps/gvim.png" },
     {"Galculator", "galculator", "/usr/share/icons/hicolor/48x48/apps/galculator.png" },
     {"HP Device Manager", "hp-toolbox", "///usr/share/hplip/data/images/128x128/hp_logo.png" },
     {"KCalc", "kcalc", "/usr/share/icons/gnome/16x16/apps/accessories-calculator.png" },
     {"KSmoothDock", "ksmoothdock", "/usr/share/icons/gnome/16x16/places/user-desktop.png" },
     {"Kate", "kate -b ", "/usr/share/icons/hicolor/16x16/apps/kate.png" },
     {"Klipper", "klipper"},
     {"Kvantum Manager", "kvantummanager"},
     {"Leafpad", "leafpad ", "/usr/share/icons/hicolor/16x16/apps/leafpad.png" },
     {"Maps", "gapplication launch org.gnome.Maps "},
     {"Mousepad", "mousepad ", "/usr/share/icons/gnome/16x16/apps/accessories-text-editor.png" },
     {"Orage Globaltime", "globaltime", "/usr/share/icons/hicolor/48x48/apps/orage_globaltime.png" },
     {"PCManFM-Qt File Manager", "pcmanfm-qt ", "/usr/share/icons/gnome/16x16/apps/system-file-manager.png" },
     {"Plank", "plank", "/usr/share/icons/hicolor/16x16/apps/plank.svg" },
     {"Redshift", "redshift-gtk"},
     {"Screenshot", "xfce4-screenshooter", "/usr/share/icons/hicolor/48x48/apps/applets-screenshooter.png" },
     {"Screenshot", "gnome-screenshot --interactive"},
     {"Software Token", "stoken-gui", "/usr/share/pixmaps/stoken-gui.png" },
     {"Software Token (small)", "stoken-gui --small", "/usr/share/pixmaps/stoken-gui.png" },
     {"SpaceFM File Search", "spacefm --find-files ", "/usr/share/icons/hicolor/48x48/apps/spacefm-find.png" },
     {"Spectacle", "qdbus org.kde.Spectacle / StartAgent", "/usr/share/icons/hicolor/16x16/apps/spectacle.png" },
     {"Text Editor", "gedit "},
     {"To Do", "gnome-todo", "/usr/share/icons/hicolor/16x16/apps/org.gnome.Todo.png" },
     {"Variety", "variety "},
     {"Vim", "xterm -e vim ", "/usr/share/icons/hicolor/48x48/apps/gvim.png" },
     {"Visual Studio Code", "/opt/visual-studio-code/code ", "/usr/share/icons/visual-studio-code.png" },
     {"Weather", "gapplication launch org.gnome.Weather"},
     {"balenaEtcher", "/opt/balenaEtcher/balena-etcher-electron ", "/usr/share/icons/hicolor/16x16/apps/balena-etcher-electron.png" },
     {"compton", "compton", "/usr/share/icons/hicolor/48x48/apps/compton.png" },
     {"nitrogen", "nitrogen", "/usr/share/icons/hicolor/16x16/apps/nitrogen.png" },
 }

 local menude7a22a0c94aa64ba2449e520aa20c99 = {
     {"LibreOffice Math", "libreoffice --math ", "/usr/share/icons/hicolor/16x16/apps/libreoffice-math.png" },
 }

 local menu251bd8143891238ecedc306508e29017 = {
     {"LTris", "ltris", "///usr/share/icons/ltris48.gif" },
     {"RetroArch", "retroarch", "/usr/share/pixmaps/retroarch.svg" },
 }

 local menud334dfcea59127bedfcdbe0a3ee7f494 = {
     {"Document Scanner", "simple-scan"},
     {"Document Viewer", "evince "},
     {"E-book Viewer", "ebook-viewer --detach ", "/usr/share/icons/hicolor/16x16/apps/calibre-viewer.png" },
     {"GNU Image Manipulation Program", "gimp-2.10 ", "/usr/share/icons/hicolor/16x16/apps/gimp.png" },
     {"Gwenview", "gwenview ", "/usr/share/icons/hicolor/16x16/apps/gwenview.png" },
     {"Image Viewer", "eog "},
     {"Image Viewer", "gpicview ", "/usr/share/icons/hicolor/48x48/apps/gpicview.png" },
     {"Inkscape", "inkscape ", "/usr/share/icons/hicolor/16x16/apps/inkscape.png" },
     {"LRF Viewer", "lrfviewer ", "/usr/share/icons/hicolor/16x16/apps/calibre-viewer.png" },
     {"LXImage", "lximage-qt ", "/usr/share/icons/hicolor/48x48/apps/lximage-qt.png" },
     {"LibreOffice Draw", "libreoffice --draw ", "/usr/share/icons/hicolor/16x16/apps/libreoffice-draw.png" },
     {"Okular", "okular ", "/usr/share/icons/hicolor/16x16/apps/okular.png" },
     {"Ristretto Image Viewer", "ristretto ", "/usr/share/icons/hicolor/16x16/apps/ristretto.png" },
     {"ScreenGrab", "screengrab", "/usr/share/icons/hicolor/32x32/apps/screengrab.png" },
     {"Screenshot", "lximage-qt --screenshot", "/usr/share/icons/gnome/16x16/devices/camera-photo.png" },
     {"Skanlite", "skanlite -qwindowtitle Skanlite ", "/usr/share/icons/gnome/16x16/devices/scanner.png" },
     {"XDvi", "xdvi "},
 }

 local menuc8205c7636e728d448c2774e6a4a944b = {
     {"Avahi SSH Server Browser", "/usr/bin/bssh", "/usr/share/icons/gnome/16x16/devices/network-wired.png" },
     {"Avahi VNC Server Browser", "/usr/bin/bvnc", "/usr/share/icons/gnome/16x16/devices/network-wired.png" },
     {"Dropbox", "dropbox", "/usr/share/pixmaps/dropbox.svg" },
     {"FileZilla", "filezilla", "/usr/share/icons/hicolor/16x16/apps/filezilla.png" },
     {"Firefox", "/usr/lib/firefox/firefox ", "/usr/share/icons/hicolor/16x16/apps/firefox.png" },
     {"Firefox Developer Edition", "/usr/lib/firefox-developer-edition/firefox ", "/usr/share/icons/hicolor/16x16/apps/firefox-developer-edition.png" },
     {"KGet", "kget -qwindowtitle KGet ", "/usr/share/icons/hicolor/16x16/apps/kget.png" },
     {"Links", "xlinks -g", "/usr/share/pixmaps/links_32x32.xpm" },
     {"Thunderbird", "/usr/lib/thunderbird/thunderbird ", "/usr/share/icons/hicolor/16x16/apps/thunderbird.png" },
     {"Web", "epiphany "},
     {"pCloud", "pcloud", "/usr/share/icons/hicolor/16x16/apps/pcloud.png" },
     {"qBittorrent", "qbittorrent ", "/usr/share/icons/hicolor/16x16/apps/qbittorrent.png" },
 }

 local menudf814135652a5a308fea15bff37ea284 = {
     {"Calendar", "gnome-calendar"},
     {"Calibre", "calibre --detach ", "/usr/share/icons/hicolor/16x16/apps/calibre-gui.png" },
     {"Dictionary", "gnome-dictionary", "/usr/share/icons/gnome/16x16/apps/accessories-dictionary.png" },
     {"Document Viewer", "evince "},
     {"E-book Editor", "ebook-edit --detach ", "/usr/share/icons/hicolor/16x16/apps/calibre-ebook-edit.png" },
     {"LibreOffice", "libreoffice ", "/usr/share/icons/hicolor/16x16/apps/libreoffice-startcenter.png" },
     {"LibreOffice Base", "libreoffice --base ", "/usr/share/icons/hicolor/16x16/apps/libreoffice-base.png" },
     {"LibreOffice Calc", "libreoffice --calc ", "/usr/share/icons/hicolor/16x16/apps/libreoffice-calc.png" },
     {"LibreOffice Draw", "libreoffice --draw ", "/usr/share/icons/hicolor/16x16/apps/libreoffice-draw.png" },
     {"LibreOffice Impress", "libreoffice --impress ", "/usr/share/icons/hicolor/16x16/apps/libreoffice-impress.png" },
     {"LibreOffice Math", "libreoffice --math ", "/usr/share/icons/hicolor/16x16/apps/libreoffice-math.png" },
     {"LibreOffice Writer", "libreoffice --writer ", "/usr/share/icons/hicolor/16x16/apps/libreoffice-writer.png" },
     {"Okular", "okular ", "/usr/share/icons/hicolor/16x16/apps/okular.png" },
     {"Orage Calendar", "orage", "/usr/share/icons/hicolor/48x48/apps/xfcalendar.png" },
     {"Orage Globaltime", "globaltime", "/usr/share/icons/hicolor/48x48/apps/orage_globaltime.png" },
     {"Texmaker", "texmaker ", "/usr/share/pixmaps/texmaker.png" },
     {"Zathura", "zathura ", "/usr/share/icons/hicolor/16x16/apps/org.pwmt.zathura.png" },
 }

 local menue6f43c40ab1c07cd29e4e83e4ef6bf85 = {
     {"Boxes", "gnome-boxes "},
     {"CMake", "cmake-gui ", "/usr/share/icons/hicolor/32x32/apps/CMakeSetup.png" },
     {"Geany", "geany ", "/usr/share/icons/hicolor/16x16/apps/geany.png" },
     {"Icon Browser", "yad-icon-browser", "/usr/share/icons/hicolor/16x16/apps/yad.png" },
     {"Qt Assistant", "assistant", "/usr/share/icons/hicolor/32x32/apps/assistant.png" },
     {"Qt Designer", "designer ", "/usr/share/icons/hicolor/128x128/apps/QtProject-designer.png" },
     {"Qt Linguist", "linguist ", "/usr/share/icons/hicolor/16x16/apps/linguist.png" },
     {"Qt QDbusViewer ", "qdbusviewer", "/usr/share/icons/hicolor/32x32/apps/qdbusviewer.png" },
     {"Visual Studio Code", "/opt/visual-studio-code/code ", "/usr/share/icons/visual-studio-code.png" },
 }

 local menu52dd1c847264a75f400961bfb4d1c849 = {
     {"Cantata", "cantata ", "/usr/share/icons/hicolor/16x16/apps/cantata.png" },
     {"Cheese", "cheese"},
     {"Elisa", "elisa ", "/usr/share/icons/hicolor/16x16/apps/elisa.png" },
     {"HandBrake", "ghb "},
     {"Kdenlive", "kdenlive ", "/usr/share/icons/hicolor/16x16/apps/kdenlive.png" },
     {"Kodi", "kodi", "/usr/share/icons/hicolor/16x16/apps/kodi.png" },
     {"LXMusic simple music player", "lxmusic", "/usr/share/pixmaps/lxmusic.png" },
     {"Lollypop", "lollypop ", "/usr/share/icons/hicolor/16x16/apps/org.gnome.Lollypop.png" },
     {"MKVToolNix GUI", "mkvtoolnix-gui ", "/usr/share/icons/hicolor/16x16/apps/mkvtoolnix-gui.png" },
     {"MediaInfo", "mediainfo-gui ", "/usr/share/icons/hicolor/256x256/apps/mediainfo.png" },
     {"Music", "gnome-music"},
     {"Parole Media Player", "parole ", "/usr/share/icons/hicolor/16x16/apps/parole.png" },
     {"PulseAudio Volume Control", "pavucontrol", "/usr/share/icons/gnome/16x16/apps/multimedia-volume-control.png" },
     {"Qt V4L2 test Utility", "qv4l2", "/usr/share/icons/hicolor/16x16/apps/qv4l2.png" },
     {"Qt V4L2 video capture utility", "qvidcap", "/usr/share/icons/hicolor/16x16/apps/qvidcap.png" },
     {"Serviio", " serviio-console", "/usr/share/icons/hicolor/48x48/apps/serviio.png" },
     {"VLC media player", "/usr/bin/vlc --started-from-file ", "/usr/share/icons/hicolor/16x16/apps/vlc.png" },
     {"Videos", "totem "},
     {"Volume Icon", "volumeicon", "/usr/share/icons/gnome/16x16/apps/multimedia-volume-control.png" },
     {"mpv Media Player", "mpv --player-operation-mode=pseudo-gui -- ", "/usr/share/icons/hicolor/16x16/apps/mpv.png" },
 }

 local menuee69799670a33f75d45c57d1d1cd0ab3 = {
     {"Alacritty", "alacritty", "/usr/share/pixmaps/Alacritty.svg" },
     {"Avahi Zeroconf Browser", "/usr/bin/avahi-discover", "/usr/share/icons/gnome/16x16/devices/network-wired.png" },
     {"Boxes", "gnome-boxes "},
     {"Bulk Rename", "/usr/lib/Thunar/ThunarBulkRename ", "/usr/share/icons/hicolor/16x16/apps/Thunar.png" },
     {"Color Profile Viewer", "gcm-viewer", "/usr/share/icons/hicolor/16x16/apps/gnome-color-manager.png" },
     {"Cool Retro Term", "cool-retro-term", "/usr/share/icons/hicolor/32x32/apps/cool-retro-term.png" },
     {"Disk Usage Analyzer", "baobab"},
     {"Dolphin", "dolphin ", "/usr/share/icons/gnome/16x16/apps/system-file-manager.png" },
     {"File Manager PCManFM", "pcmanfm ", "/usr/share/icons/gnome/16x16/apps/system-file-manager.png" },
     {"GParted", "/usr/bin/gparted ", "/usr/share/icons/hicolor/16x16/apps/gparted.png" },
     {"Htop", "xterm -e htop", "/usr/share/pixmaps/htop.png" },
     {"KDE Partition Manager", "partitionmanager"},
     {"KSysGuard", "ksysguard ", "/usr/share/icons/gnome/16x16/apps/utilities-system-monitor.png" },
     {"KSystemLog", "/usr/bin/kdesu ksystemlog -qwindowtitle KSystemLog"},
     {"KWalletManager", "kwalletmanager5 ", "/usr/share/icons/hicolor/16x16/apps/kwalletmanager.png" },
     {"Konsole", "konsole", "/usr/share/icons/gnome/16x16/apps/utilities-terminal.png" },
     {"LSHW", "/usr/sbin/gtk-lshw", "///usr/share/lshw/artwork/logo.svg" },
     {"LXTerminal", "lxterminal", "/usr/share/icons/hicolor/128x128/apps/lxterminal.png" },
     {"Logs", "gnome-logs"},
     {"Manage Printing", "/usr/bin/xdg-open http://localhost:631/", "/usr/share/icons/hicolor/16x16/apps/cups.png" },
     {"Octopi", "/usr/bin/octopi"},
     {"Octopi CacheCleaner", "/usr/bin/octopi-cachecleaner"},
     {"Octopi Notifier", "/usr/bin/octopi-notifier"},
     {"Oracle VM VirtualBox", "VirtualBox ", "/usr/share/icons/hicolor/16x16/mimetypes/virtualbox.png" },
     {"Package Updater", "gpk-update-viewer", "/usr/share/icons/gnome/16x16/apps/system-software-update.png" },
     {"Packages", "gpk-application", "/usr/share/icons/hicolor/16x16/apps/system-software-install.svg" },
     {"QTerminal", "qterminal", "/usr/share/icons/gnome/16x16/apps/utilities-terminal.png" },
     {"QTerminal drop down", "qterminal --drop", "/usr/share/icons/gnome/16x16/apps/utilities-terminal.png" },
     {"SUSE Studio Imagewriter", "imagewriter ", "/usr/share/icons/hicolor/32x32/apps/imagewriter.png" },
     {"Software", "gnome-software "},
     {"SpaceFM", "spacefm ", "/usr/share/icons/hicolor/48x48/apps/spacefm.png" },
     {"Startup Disk Creator", "usb-creator-kde"},
     {"System Monitor", "gnome-system-monitor"},
     {"System Profiler and Benchmark", "/usr/bin/hardinfo", "/usr/share/icons/hicolor/48x48/apps/hardinfo.png" },
     {"System Settings", "io.elementary.switchboard ", "/usr/share/icons/gnome/16x16/categories/preferences-desktop.png" },
     {"Task Manager", "lxtask", "/usr/share/icons/gnome/16x16/apps/utilities-system-monitor.png" },
     {"Task Manager", "xfce4-taskmanager", "/usr/share/icons/gnome/16x16/apps/utilities-system-monitor.png" },
     {"Terminal", "gnome-terminal"},
     {"Terminator", "terminator", "/usr/share/icons/hicolor/16x16/apps/terminator.png" },
     {"Termite", "termite", "/usr/share/icons/gnome/16x16/apps/utilities-terminal.png" },
     {"Thunar File Manager", "thunar ", "/usr/share/icons/hicolor/16x16/apps/Thunar.png" },
     {"Tint2", "tint2"},
     {"UXTerm", "uxterm", "/usr/share/pixmaps/xterm-color_48x48.xpm" },
     {"Virtual Machine Manager", "virt-manager", "/usr/share/icons/hicolor/16x16/apps/virt-manager.png" },
     {"XTerm", "xterm", "/usr/share/pixmaps/xterm-color_48x48.xpm" },
     {"Xfce Terminal", "xfce4-terminal", "/usr/share/icons/gnome/16x16/apps/utilities-terminal.png" },
     {"conky", "conky --daemonize --pause=1"},
     {"jgmenu", "jgmenu_run"},
     {"kitty", "kitty", "/usr/share/icons/hicolor/256x256/apps/kitty.png" },
     {"ranger", "xterm -e ranger", "/usr/share/icons/gnome/16x16/apps/utilities-terminal.png" },
     {"urxvt", "urxvt", "/usr/share/icons/gnome/16x16/apps/utilities-terminal.png" },
     {"urxvt (client)", "urxvtc", "/usr/share/icons/gnome/16x16/apps/utilities-terminal.png" },
     {"urxvt (tabbed)", "urxvt-tabbed", "/usr/share/icons/gnome/16x16/apps/utilities-terminal.png" },
 }

xdgmenu = {
    {"Accessories", menu98edb85b00d9527ad5acebe451b3fae6},
    {"Education", menude7a22a0c94aa64ba2449e520aa20c99},
    {"Games", menu251bd8143891238ecedc306508e29017},
    {"Graphics", menud334dfcea59127bedfcdbe0a3ee7f494},
    {"Internet", menuc8205c7636e728d448c2774e6a4a944b},
    {"Office", menudf814135652a5a308fea15bff37ea284},
    {"Programming", menue6f43c40ab1c07cd29e4e83e4ef6bf85},
    {"Sound & Video", menu52dd1c847264a75f400961bfb4d1c849},
    {"System Tools", menuee69799670a33f75d45c57d1d1cd0ab3},
}


  mymainmenu = awful.menu({
    items = {
      {"Terminal", terminal},
      -- Replace the alphabets with the list generated by xdg_menu
      {"Applications", xdgmenu}, 
      {"Awesome", myawesomemenu},
      {"Take a Screenshot", screenshot},
      {"End Session", function() _G.exit_screen_show() end},
    }
  })

  mylauncher = awful.widget.launcher({ image = beautiful.awesome_icon, menu = mymainmenu })

end

-- Embed mouse bindings
root.buttons(gears.table.join(awful.button({ }, 3, function () mymainmenu:toggle() end)))
