-- TO GENERATE MENU YOU NEED TO INSTALL XDG-MENU
-- IF YOURE USING ARCH IT IS CALLED `archlinux-xdg-menu`
-- THEN EXECUTE
-- xdg_menu --format awesome --root-menu /etc/xdg/menus/arch-applications.menu >~/.config/awesome/archmenu.lua
-- IT WILL GENERATE A MENU LIST IN archmenu.lua
-- Just substitute or transfer the generated list to this module.

local awful = require("awful")
local gears = require("gears")
local beautiful = require("beautiful")
local apps = require('configuration.apps')
local hotkeys_popup = require('awful.hotkeys_popup').widget

terminal = apps.default.terminal
editor = os.getenv("EDITOR") or "nano"
editor_cmd = terminal .. " -e " .. editor


-- Theming Menu
beautiful.menu_font = "SFNS Display Regular 10"
beautiful.menu_submenu = '' -- ➤

-- {{{ Menu
-- Create a launcher widget and a main menu
myawesomemenu = {
  { "Hotkeys", function() hotkeys_popup.show_help(nil, awful.screen.focused()) end },
  { "Edit config", editor_cmd .. " " .. awesome.conffile },
  { "Restart", awesome.restart },
  { "Quit", function() awesome.quit() end },
}

-- Replace with the list generated by xdg_menu
  menue0e4fc6213e8b3593495a7260c3a4c2e = {
      {"Xmag", "xmag"},
  }

  menub196cfab1f918dcd1cca1befa53fe5b8 = {
      {"Xedit", "xedit"},
  }

  menud334dfcea59127bedfcdbe0a3ee7f494 = {
      {"X Window Snapshot", "xwd | xwud"},
  }

   menu07a3dd247ad6bec7fe401aa11619959f = {
       {"Telnet", "xterm -e /usr/bin/telnet.netkit"},
       {"Xbiff", "xbiff"},
   }

  menueec89088ee408b80387155272b113256 = {
    {"Communication", menu07a3dd247ad6bec7fe401aa11619959f},
  }

  menue6f43c40ab1c07cd29e4e83e4ef6bf85 = {
      {"GDB", "xterm -e /usr/bin/gdb"},
      {"Monodoc (http)", "xterm -e /usr/bin/monodoc-http", "///usr/share/pixmaps/monodoc.xpm" },
      {"Tclsh8.6", "xterm -e /usr/bin/tclsh8.6"},
      {"TkWish8.6", "x-terminal-emulator -e /usr/bin/wish8.6"},
  }

   menu540b21ecdb276f5087ee585cedd6d5d0 = {
       {"Bc", "xterm -e /usr/bin/bc"},
       {"Xcalc", "xcalc"},
       {"sympy (Python2)", "xterm -e python2 /usr/bin/isympy"},
   }

  menu35bf1210e6727959a7a88a00462db959 = {
    {"Mathematics", menu540b21ecdb276f5087ee585cedd6d5d0},
  }

  menub8351fe00838453b164398bed581ac97 = {
      {"Bash", "xterm -e /bin/bash --login"},
      {"Dash", "xterm -e /bin/dash -i"},
      {"Sh", "xterm -e /bin/sh --login"},
  }

  menu9d07e0e08af7f96cf45be0112b9ccfbe = {
      {"ncmpcpp", "konsole -e /usr/bin/ncmpcpp"},
  }

   menu7258e7251413465e0a3eb58094430bde = {
       {"Debian Task selector", "xterm -e su-to-root -c tasksel"},
       {"Editres", "editres"},
       {"Xclipboard", "xclipboard"},
       {"Xfontsel", "xfontsel"},
       {"Xkill", "xkill"},
       {"Xrefresh", "xrefresh"},
   }

   menu3c02a379965ab0dfcd77b1c484450433 = {
       {"Xvidtune", "xvidtune"},
   }

   menu423e555c5ec3885f2bb5d9d2d6627f63 = {
       {"Pstree", "xterm -e /usr/bin/pstree.x11", "///usr/share/pixmaps/pstree16.xpm" },
       {"Top", "xterm -e /usr/bin/top"},
       {"Xconsole", "xconsole -file /dev/xconsole"},
       {"Xev", "x-terminal-emulator -e xev"},
       {"Xload", "xload"},
   }

   menu26fb3d624c05690c2f66387de49a4ca6 = {
       {"Synaptic Package Manager", "x-terminal-emulator -e synaptic-pkexec", "///usr/share/synaptic/pixmaps/synaptic_32x32.xpm" },
   }

  menua45da96d0bf6575970f2d27af22be28a = {
    {"Administration", menu7258e7251413465e0a3eb58094430bde},
    {"Hardware", menu3c02a379965ab0dfcd77b1c484450433},
    {"Monitoring", menu423e555c5ec3885f2bb5d9d2d6627f63},
    {"Package Management", menu26fb3d624c05690c2f66387de49a4ca6},
  }

  menud93a7d4284e96048163ffeb1ce9b308c = {
      {"Wordview", "/usr/bin/wordview"},
      {"Xditview", "xditview"},
  }

 local menu1ddf333c6654f7f89c739dddfb4cc429 = {
    {"Accessibility", menue0e4fc6213e8b3593495a7260c3a4c2e},
    {"Editors", menub196cfab1f918dcd1cca1befa53fe5b8},
    {"Graphics", menud334dfcea59127bedfcdbe0a3ee7f494},
    {"Network", menueec89088ee408b80387155272b113256},
    {"Programming", menue6f43c40ab1c07cd29e4e83e4ef6bf85},
    {"Science", menu35bf1210e6727959a7a88a00462db959},
    {"Shells", menub8351fe00838453b164398bed581ac97},
    {"Sound", menu9d07e0e08af7f96cf45be0112b9ccfbe},
    {"System", menua45da96d0bf6575970f2d27af22be28a},
    {"Viewers", menud93a7d4284e96048163ffeb1ce9b308c},
 }

  menu66d0af2d5da0109dc2aae67829f7d4d4 = {
      {"Oclock", "oclock"},
      {"Xclock (analog)", "xclock -analog"},
      {"Xclock (digital)", "xclock -digital -update 1"},
      {"Xeyes", "xeyes"},
      {"Xlogo", "xlogo"},
  }

 local menu251bd8143891238ecedc306508e29017 = {
    {"Toys", menu66d0af2d5da0109dc2aae67829f7d4d4},
 }

 local menu6a26f548831e6a8c26bfbbd9f6ec61e0 = {
     {"Xman", "xman"},
 }

xdgmenu = {
    {"Applications", menu1ddf333c6654f7f89c739dddfb4cc429},
    {"Games", menu251bd8143891238ecedc306508e29017},
    {"Help", menu6a26f548831e6a8c26bfbbd9f6ec61e0},
}



mymainmenu = awful.menu({
  items = {
    {"Apps", menu1ddf333c6654f7f89c739dddfb4cc429},
    {"Awesome", myawesomemenu},
    {"End Session", function() _G.exit_screen_show() end},
  }
})

mylauncher = awful.widget.launcher({ image = beautiful.awesome_icon, menu = mymainmenu })

-- Embed mouse bindings
root.buttons(gears.table.join(awful.button({ }, 3, function () mymainmenu:toggle() end)))
